services:
  - type: web
    name: fashion-style-finder
    env: python
    buildCommand: poetry install
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: PORT
        value: 8000